/**
 * Blog controller.
 * Handles all CRUD operations for blog posts.
 */

const Post = require("../models/Post");

// ---------------------------------------------------------------------------
// getPosts
// ---------------------------------------------------------------------------

/**
 * GET /api/blog/posts
 * Query params: page, limit, search, category, tag
 *
 * - Public users see only published posts
 * - Admins can optionally filter by status
 * - Supports full-text search on title, excerpt, and tags
 * - Populates author name + avatar
 * - Sorted by createdAt descending (newest first)
 */
const getPosts = async (req, res) => {
  try {
    const page = Math.max(1, parseInt(req.query.page) || 1);
    const limit = Math.min(50, Math.max(1, parseInt(req.query.limit) || 9));
    const skip = (page - 1) * limit;

    const { search = "", category = "", tag = "", status } = req.query;

    // Build query filter
    const filter = {};

    // Non-admins can only see published posts
    const isAdmin = req.user && req.user.role === "admin";
    if (!isAdmin) {
      filter.status = "published";
    } else if (status && ["published", "draft"].includes(status)) {
      filter.status = status;
    }

    // Category filter
    if (category) {
      filter.category = category;
    }

    // Tag filter
    if (tag) {
      filter.tags = { $in: [tag] };
    }

    // Text search across title, excerpt, and tags
    if (search) {
      const regex = new RegExp(search, "i");
      filter.$or = [
        { title: regex },
        { excerpt: regex },
        { tags: { $in: [regex] } },
      ];
    }

    const [posts, total] = await Promise.all([
      Post.find(filter)
        .populate("author", "name avatar")
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .lean(),
      Post.countDocuments(filter),
    ]);

    const pages = Math.ceil(total / limit);

    return res.status(200).json({
      success: true,
      data: { posts, total, pages, page },
    });
  } catch (error) {
    console.error("getPosts error:", error);
    return res.status(500).json({ success: false, message: "Server error." });
  }
};

// ---------------------------------------------------------------------------
// getPost
// ---------------------------------------------------------------------------

/**
 * GET /api/blog/posts/:slug
 *
 * - Fetches a single post by slug
 * - Increments view counter (non-blocking)
 * - Non-admins can only view published posts
 */
const getPost = async (req, res) => {
  try {
    const { slug } = req.params;

    const filter = slug.match(/^[0-9a-fA-F]{24}$/) ? { _id: slug } : { slug };
    const isAdmin = req.user && req.user.role === "admin";
    if (!isAdmin) {
      filter.status = "published";
    }

    const post = await Post.findOne(filter)
      .populate("author", "name avatar bio")
      .lean();

    if (!post) {
      return res
        .status(404)
        .json({ success: false, message: "Post not found." });
    }

    // Increment view count (fire-and-forget)
    Post.findByIdAndUpdate(post._id, { $inc: { views: 1 } }).catch(() => {});

    return res.status(200).json({ success: true, data: post });
  } catch (error) {
    console.error("getPost error:", error);
    return res.status(500).json({ success: false, message: "Server error." });
  }
};

// ---------------------------------------------------------------------------
// createPost
// ---------------------------------------------------------------------------

/**
 * POST /api/blog/posts  (admin only)
 * Body: { title, content, excerpt, coverImage, category, tags, status }
 *
 * - Slug is auto-generated by the Post pre-save hook
 * - Author is set to the authenticated admin
 */
const createPost = async (req, res) => {
  try {
    const { title, content, excerpt, coverImage, category, tags, status } =
      req.body;

    if (!title || !content || !category) {
      return res.status(400).json({
        success: false,
        message: "Title, content, and category are required.",
      });
    }

    const post = await Post.create({
      title,
      content,
      excerpt: excerpt || "",
      coverImage: coverImage || "",
      category,
      tags: Array.isArray(tags) ? tags : [],
      status: status || "draft",
      author: req.user._id,
    });

    // Populate author for the response
    await post.populate("author", "name avatar");

    return res.status(201).json({ success: true, data: post });
  } catch (error) {
    console.error("createPost error:", error);
    if (error.name === "ValidationError") {
      const messages = Object.values(error.errors).map((e) => e.message);
      return res
        .status(400)
        .json({ success: false, message: messages.join(", ") });
    }
    return res.status(500).json({ success: false, message: "Server error." });
  }
};

// ---------------------------------------------------------------------------
// updatePost
// ---------------------------------------------------------------------------

/**
 * PUT /api/blog/posts/:id  (admin only)
 *
 * - Finds post by ID and applies updates
 * - Slug is regenerated if title changes (handled by pre-save hook)
 */
const updatePost = async (req, res) => {
  try {
    const { id } = req.params;
    const { title, content, excerpt, coverImage, category, tags, status } =
      req.body;

    const post = await Post.findById(id);
    if (!post) {
      return res
        .status(404)
        .json({ success: false, message: "Post not found." });
    }

    // Apply only provided fields
    if (title !== undefined) post.title = title;
    if (content !== undefined) post.content = content;
    if (excerpt !== undefined) post.excerpt = excerpt;
    if (coverImage !== undefined) post.coverImage = coverImage;
    if (category !== undefined) post.category = category;
    if (tags !== undefined) post.tags = Array.isArray(tags) ? tags : [];
    if (status !== undefined) post.status = status;

    await post.save();
    await post.populate("author", "name avatar");

    return res.status(200).json({ success: true, data: post });
  } catch (error) {
    console.error("updatePost error:", error);
    if (error.name === "ValidationError") {
      const messages = Object.values(error.errors).map((e) => e.message);
      return res
        .status(400)
        .json({ success: false, message: messages.join(", ") });
    }
    return res.status(500).json({ success: false, message: "Server error." });
  }
};

// ---------------------------------------------------------------------------
// deletePost
// ---------------------------------------------------------------------------

/**
 * DELETE /api/blog/posts/:id  (admin only)
 */
const deletePost = async (req, res) => {
  try {
    const { id } = req.params;

    const post = await Post.findByIdAndDelete(id);
    if (!post) {
      return res
        .status(404)
        .json({ success: false, message: "Post not found." });
    }

    return res.status(200).json({
      success: true,
      message: "Post deleted successfully.",
    });
  } catch (error) {
    console.error("deletePost error:", error);
    return res.status(500).json({ success: false, message: "Server error." });
  }
};

// ---------------------------------------------------------------------------
// toggleStatus
// ---------------------------------------------------------------------------

/**
 * PATCH /api/blog/posts/:id/status  (admin only)
 * Body: { status: 'published' | 'draft' }
 *
 * - Explicitly sets the status to the provided value
 */
const toggleStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { status } = req.body;

    if (!status || !["published", "draft"].includes(status)) {
      return res.status(400).json({
        success: false,
        message: "Status must be 'published' or 'draft'.",
      });
    }

    const post = await Post.findByIdAndUpdate(
      id,
      { status },
      { new: true, runValidators: true }
    ).populate("author", "name avatar");

    if (!post) {
      return res
        .status(404)
        .json({ success: false, message: "Post not found." });
    }

    return res.status(200).json({ success: true, data: post });
  } catch (error) {
    console.error("toggleStatus error:", error);
    return res.status(500).json({ success: false, message: "Server error." });
  }
};

module.exports = {
  getPosts,
  getPost,
  createPost,
  updatePost,
  deletePost,
  toggleStatus,
};